### PR TITLE
point drawn event

### PR DESCRIPTION
**Pull request by profispojka**
Added a pointdrawn event to be able to watch drawing in realtime.

### CODE REVIEW

**Comment by profispojka** [comment]
Hi @jakubfiala. When do you think this could be merged?

**Comment by MentalGear** [comment]
This is great, thx @profispojka . Since you have knowledge on draw eventsm any chance you could also take a look at https://github.com/jakubfiala/atrament.js/issues/53 ?

**Comment by profispojka** [comment]
@MentalGear Well, if this merge request will be merged, I could then have a look.

**Comment by jakubfiala** [comment]
@profispojka I'm really sorry I have not been responsive in the last year, I let things slip a bit and couldn't focus on maintaining the library. I'm going to review the PR and merge it on Monday, I've planned some time for Atrament maintenance then. Thank you for your patience and perseverance :)

**Comment by jakubfiala** [comment]
@profispojka thank you for the PR! I do want to include this new event, but I think I'd like to implement it slightly differently, so some of the existing code is reused. Will open another PR and tag you in it so you're kept in the loop :) thanks again!

**Pull request closed without merging**
