### PR TITLE
Issue #3

### PR DESCRIPTION
**Pull request by ptkach**
Bucket fill added. Please check.

### CODE REVIEW

**Comment by jakubfiala** [comment]
awesome! it's really fast, too. From my testing, it works perfectly on FF, but on WebKit browsers there is probably some aliasing so a bunch of unfilled pixels always remain at the edges of the blob.

Also it doesn't work on Safari 9 (does work on the Tech Preview), haven't checked mobile yet. This seems to be a transpiling problem, will look into it.

Let's keep this open for now, I'll work on the code a bit today if you don't have time.

Thanks a lot for your contribution, it's very cool!!

**Comment by jakubfiala** [comment]
Okay, found the problem – in Safari <=9, `ImageData.data` is an `UInt8ClampedArray`, not an `Array`, so it cannot be destructured.

Gonna look into the aliasing now.

**Comment by ptkach** [comment]
Hi,
Nice catch with Safari, I didn't check that. Any success with aliasing? I will also look into it today.

**Comment by jakubfiala** [comment]
Working on it now – one way that I was able to make it look better is to modify `matchColor` so that it measures the euclidean distance from the start color, and returns true if the distance is smaller than threshold. However, it seems to sometimes end up in an infinite loop, especially if the start and fill colors are similar.

Also, I think doing recursion in cartesian space is slightly faster, this code works quite well:
```js
		let context = this.context,
			canvasWidth = context.canvas.width,
			canvasHeight = context.canvas.height,
			//hex needs to be trasformed to rgb since colorLayer accepts RGB
			[fillR, fillG, fillB] = hexToRgb(this.color),
			//Need to save current context with colors, we will update it
			colorLayer = context.getImageData(0, 0, context.canvas.width, context.canvas.height);

		let cartTo1D = (_x, _y) => (_y * canvasWidth + _x) * 4;

		function desc(x, y) {
			let pos = cartTo1D(x, y);

			if (matchStartColor(pos)) {
				colorPixel(pos, fillR, fillG, fillB);
				desc(x + 1, y);
				desc(x - 1, y);
				desc(x, y + 1);
				desc(x, y - 1);
			}
			else return;
		}

		desc(startX, startY);
```

what do you think?

**Comment by jakubfiala** [comment]
actually, it doesn't work, as it exceeds the call stack pretty fast.

**Comment by jakubfiala** [comment]
okay, managed to make it look a lot better by actually "aliasing" the neighbour pixels when a pixel is colored. Here's what it looks like now:
antialias
Not perfect, but I'd say that will do.

I'm going to do a bunch of other optimizations, as for instance now if you click twice rapidly in fill mode, the first loop doesn't finish yet and the algorithm gets a bit slow. Also going to make the fill method use the global alpha setting.

Is it okay if I modify this PR?

**Comment by ptkach** [comment]
Whatever fits you better =) I don't mind if you send me the code you are looking for and I will push it, which will update PR automatically and you will be able to merge.

**Comment by jakubfiala** [comment]
Okay, let's do that. Just sorted out transparency (so now we don't need to have a white background initially), now looking into the rapid trigger issue. One question: is there a particular reason why the fill mode is a separate state from draw & erase?

Because personally, I'd prefer it to be more like `atrament.mode = 'fill' || 'draw' || 'erase';`. Erasing large areas with the paint bucket is cool, but not sure how useful it would be. People can always fill with zero opacity for the same effect.

**Comment by ptkach** [comment]
Yeah, you are right. I was also planning to add it as a third mode, before I thought it can be used as eraser also, didn't reach zero opacity tho

**Comment by jakubfiala** [comment]
Hey, so I've finished my modifications, here's the zipped repo, `src/atrament.js` and `demo/index.html` are the only files I've changed:
[atrament.js-bucketFill.zip](https://github.com/jakubfiala/atrament.js/files/217242/atrament.js-bucketFill.zip)

Let me know if it works for you. I have a weird feeling that the filling used to be a bit faster, particularly when filling the whole canvas. But maybe I'm wrong.

**Comment by ptkach** [comment]
Hi, Thank you. 
It works like a charm for me. Yes, it's a bit slower, but it only noticeable on full canvas filling.

**Comment by jakubfiala** [comment]
Cool! any changes you'd like to make before I merge?

**Comment by ptkach** [comment]
I have nothing to add at this point. I will might look at performance later, but I think it makes sense to fix it as a separate issue

**Comment by jakubfiala** [comment]
Sure, sounds good. I'm going to merge this, but I'll wait for #2 to be fixed before releasing v0.2.0

Thanks a lot for your help @ptkach

**Pull request merged**
