### PR TITLE
Issue #5

### PR DESCRIPTION
**Pull request by ptkach**
Couple fixes on bucket filling which improves the speed in several times.

### CODE REVIEW

**Comment by jakubfiala** [comment]
Awesome, it's really fast on my mac! It also actually looks a lot better! 👍

**Comment by jakubfiala** [comment]
Before I merge this, let's wait for @bradmartin to see if #5 is resolved in this.

**Comment by bradmartin** [comment]
Don't wait on me @jakubfiala - I won't have time to test it for a while. If you update the demo I can try it out much faster than running locally right now at work :smile:

**Comment by jakubfiala** [comment]
okay, I'll merge this then

**Pull request merged**
